### ISSUE TITLE
关于树形表格样式错位的问题

### ISSUE THREAD

**Issue by Typ518** [vbenjs/vue-vben-admin-doc#30]
![图片](https://user-images.githubusercontent.com/56617431/125710345-74657b7a-edff-4e4d-848a-2b68913228bf.png)
主要问题就是，我使用的是树形表格展示的数据；当数据多的时候表头和表格的样式就错位了。上面的图就是效果图。

**Comment by zhanglolo** [comment]
这个应该是滚动条导致的吧

**Comment by Typ518** [comment]
是的，看看怎么优化一下，。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月15日(星期天) 中午1:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anncwb/vue-vben-admin-doc] 关于树形表格样式错位的问题 (#30)





 
这个应该是滚动条导致的吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Typ518** [comment]
还有就是请问，对于使用ApiSelect控件联动效果没有执行OnSelect事件。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin-doc] 关于树形表格样式错位的问题 (#30)





 
这个应该是滚动条导致的吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Typ518** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin-doc] 关于树形表格样式错位的问题 (#30)





 
这个应该是滚动条导致的吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangjue666** [comment]
可以看下这个 issue https://github.com/vbenjs/vue-vben-admin/issues/3085, 已提供解决方案
