### ISSUE TITLE
重新安装依赖后启动报错

### ISSUE THREAD

**Issue by xuwoool** [vbenjs/vue-vben-admin-doc#62]
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

**Comment by Free-Qi** [comment]
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling  同样出了这个问题，有解决方案么？

**Comment by QiYoe** [comment]
在vite.config.ts文件中加上
![image](https://user-images.githubusercontent.com/36325188/168949186-82c73ce4-2367-418b-8e59-7ec1f4fb798f.png)

随后yarn dev。终端可能不显示本地启动地址（localhost:3000），不用管，直接在浏览器输入 http://localhost:3000 就可以了

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin-doc/pull/120  这个PR已修复
