### ISSUE TITLE
线上文档网站打不开了

### ISSUE THREAD

**Issue by chf-gh** [vbenjs/vue-vben-admin-doc#97]
线上文档无法打开，显示的都是文件
![image](https://user-images.githubusercontent.com/20312535/195509069-f2f782be-20aa-40e6-b37c-54191b5475ba.png)

**Comment by horizon188** [comment]
什么时候好饿

**Comment by SXZXD** [comment]
本地自己起服务先

**Comment by liujianchao1995** [comment]
github pages地址被改成  [https://vbenjs.github.io/vue-vben-admin-doc/ ](https://vbenjs.github.io/vue-vben-admin-doc/ ) 了
